umpf: add support for libcamera
pengutronix/umpf pull request #18
Opened 2023-03-10 05:21 UTC by mriesch-wv

libcamera uses Semantic Versioning, which allows for build metadata:
"Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version." [0]
    
Adjust the extraversion generation accordingly for libcamera.

[0] https://semver.org/#spec-item-10

Closes #11

2023-03-10 13:00 UTC, michaelolbrich requested changes

2023-03-10 13:00 UTC, michaelolbrich commented on umpf
> +		fi
It's not that simple.
- the grep only makes sense if the tree is in a defined state, so do that part in `rebase_base()` after the checkout.
- `version)` below checks for the `-` for `${STABLE}` = `true`, so we need to know the separator there as well. Split `${VERSION}` into `VERSION_SEPARATOR=-` and `VERSION=1` and overwrite the separator. And add it in `bailout()`

2023-03-10 13:00 UTC, michaelolbrich commented on umpf
> +		if grep -sq "project('libcamera'," "${meson_build}"; then
don't grep again, just match on something from above, `VERSION_SEPARATOR` or add something explicit. If another project needs this then I want to modify only one place.

2023-04-20 15:36 UTC, mriesch-wv commented on umpf
> +		fi
OK, I tried to implement this. Not sure whether I have slayed all occurrences, but it is worth a shot.

2023-04-20 15:36 UTC, mriesch-wv commented on umpf
> +		if grep -sq "project('libcamera'," "${meson_build}"; then
Makes sense, rewrote this part.

2023-05-05 10:39 UTC, michaelolbrich approved these changes

2023-05-05 10:41 UTC, merged