umpf: support piping yes into umpf
pengutronix/umpf pull request #50
Opened 2024-11-27 12:02 UTC by a3f

When building or tagging an umpf, umpf can ask which branch to use when multiple are available. Piping `yes(1)` into umpf in this case doesn't work, because the variable populated by read in that case is left empty.

Handle this case to reduce user confusion.

2024-12-19 09:02 UTC, a3f commented
Ok, but doesn't it make sense to have piping yes behave as expected as well?

2024-12-19 09:48 UTC, michaelolbrich commented
The problem I have with piping yes is, that is overwrites all reads. So umpf will not stop here:
https://github.com/pengutronix/umpf/blob/1a9792e2c6a71fb5b6c9f756f18d6512da491600/umpf#L473

And I think that's a really bad idea.

2024-12-19 13:48 UTC, a3f commented
Fair point. I would rename the option then though. How about `--default`?

2024-12-19 14:52 UTC, michaelolbrich commented
Sounds good.

2025-01-31 07:01 UTC, michaelolbrich requested changes
Just a few, mostly cosmetic things left.

2025-01-31 07:01 UTC, michaelolbrich commented on umpf
> +}
Please use `${...}` for all variables. We're not fully consistent overall, but it used in most cases.
And `choice` schould be a local variable.

Same everywhere else.

2025-01-31 07:01 UTC, michaelolbrich commented on umpf
> +		name=$choice
```suggestion
		name="${choice}"
```
Quote and {}

2025-01-31 07:01 UTC, michaelolbrich commented on umpf
> +		BASE=$choice
Same here.

2025-01-31 07:31 UTC, a3f commented on umpf
> +}
choice is intentionally not local, so it can be used outside the function. I am not good enough at bash to make it work with a local, can you elaborate?

2025-01-31 08:03 UTC, michaelolbrich commented on umpf
> +}
Ah, sorry, I put that comment in the wrong place. It should be local in the _calling_ function.

2025-01-31 09:02 UTC, a3f commented on umpf
> +}
My understanding was that choice as written by read_interactive is a global variable, so the callers need to access to `choice` global variable. I need to try out whether it still works with local in the calling function

2025-01-31 09:24 UTC, michaelolbrich commented on umpf
> +}
A local variable in bash is valid until the end of the function, including all functions that are called within that function.

2025-02-12 14:23 UTC, michaelolbrich approved these changes
Looks good now, thanks.

2025-02-12 14:24 UTC, merged